title: staytuned.one
description: Posts Reminder Ubuntu
show_downloads: true
google_analytics:
theme: jekyll-theme-hacker

plugins:
 - jekyll-seo-tag

github_username: staytuned4
email: sebb@tutanota.de

paginate: 7
paginate_path: "/blog/:num/"




