title: [StayTuned4]
description: Posts Reminder Ubuntu
show_downloads: true
google_analytics:
theme: jekyll-theme-hacker

plugins:
 - jekyll-seo-tag

github_username: staytuned4
email: staytuned4@tutanota.de

paginate: 7
   "/blog/:num/"

google_analytics: [staytuned4]


